### ISSUE TITLE
Old snapshot request

### ISSUE THREAD

**Issue by MiaZmy0729** [BNB48Club/bsc-snapshots#11]
Could you please upload some old snapshots? For example, the snapshot for March 2022. 
I tried to randomly generate the link by changing the block number as follows:
aria2c -s14 -x14 -k100M https://snapshots.bnb48.club/geth.19149098.tar.lz4 -o geth.tar.lz4
but it does not work.
Really appreciate your help.

**Comment by 48ClubIan** [comment]
No we will not.
