### ISSUE TITLE
geth.19682108.tar.lz4

### ISSUE THREAD

**Issue by zhusheng8701** [BNB48Club/bsc-snapshots#15]
首先感谢您提供的下载资源。
我正在下载 geth.19682108.tar.lz4 ，目前尚未完成，但已经无资源了。
能否继续开放下载呢，谢谢。
英文翻译由机器提供，请谅解！

First of all, thank you for providing download resources.
I'm downloading "geth.19682108.tar.lz4" has not been completed yet, but there are no resources.
Could you keep it open for a while? Thank you。
English translation is provided by machine, please understand!

**Comment by du5** [comment]
我们的快照每日更新一次，在新快照发布后的一小时将删除旧快照，请确保下行网络带宽大于100mbps，否则可能无法完成下载。

**Comment by zhusheng8701** [comment]
因为确实不清楚有这个机制，我们从昨天中午开始下载，已经完成了约80%，烦请能否让旧快照继续一下呢。。非常非常感谢。

**Comment by du5** [comment]
无法恢复，没有备份数据

**Comment by zhusheng8701** [comment]
😂😂😂😂😂

**Comment by du5** [comment]
😅不是不恢复，是没办法恢复 每日发布时间都差不多，可以通过下行带宽预估下载所需时间，确保能完成下载

**Comment by zhusheng8701** [comment]
100M的带宽下载这个资源需要约13小时。如果在工作时间开始进行下载处理，一定有下载不完的风险。。
两个建议：
1.此项目中写明建议
2.保留时间长一些。

**Comment by zhusheng8701** [comment]
100m的带宽，我就算从现在开始进行下载，在下次更新（20时）前我也没有办法确保可以下载完成。😂😂

**Comment by du5** [comment]
我们团队内部会发起针对此问题的讨论，如果有更新我会更新评论

**Comment by du5** [comment]
我们预计将于本月 23 日进行调整频率

- 快照打包周期 24 小时 -> 36 小时
- 发布新快照后上一份快照保留时间 1 小时 -> 12 小时
