### ISSUE TITLE
erigon-snapshots这个是全节点快照吗？

### ISSUE THREAD

**Issue by lusiwei** [BNB48Club/bsc-snapshots#16]
现在搭建全节点只能从第0个区块开始同步了吗？好像都不提供全节点快照数据了

**Comment by du5** [comment]
都是全节点快照, 不是存档节点

**Comment by lusiwei** [comment]
是修剪过的快照吗？还是完整的

**Comment by du5** [comment]
https://github.com/BNB48Club/bsc-snapshots#flags-1

https://github.com/ledgerwatch/erigon#beacon-chain

**Comment by lusiwei** [comment]
如果只想要指定区块后面的历史数据是不是加这个参数就行了--prune= --prune.h.before=18400000 --prune.r.before=18400000 --prune.t.before=18400000 --prune.c.before=18400000 , 这样配置参数是不是意味着只修剪18400000之前的区块

**Comment by du5** [comment]
是 但是 erigon 无法修改参数

**Comment by lusiwei** [comment]
你们提供的这个快照是默认5000之后的区块都修剪吗

**Comment by du5** [comment]
只保留 5k 区块

**Comment by lusiwei** [comment]
我搭建这个节点主要是想用作自建the graph node 节点的rpc节点，graph索引的合约是在18400000区块左右部署的，子图里面会调用eth.getBlockNumber()这个方法，修剪后的数据查不到这个块的数据，所以现在只能从第0区块开始同步吗，没法用这个快照

**Comment by du5** [comment]
只能从 0 开始 大概需要耗时 12 天

**Comment by lusiwei** [comment]
![image](https://user-images.githubusercontent.com/32103164/181455007-8e68e462-f54d-48c6-bed4-54a186bc7ae2.png)
这个我同步的速度，现在才到Execution阶段，每秒才同步20个快，到后面估计更慢

**Comment by du5** [comment]
Mgas/s ≈ 500 时 需要耗时 12 天, 你可以换一台高主频的服务器用来同步

**Comment by lusiwei** [comment]
服务器配置可以推荐下吗，我现在用的Amazon的i3.4xlarge实例

**Comment by du5** [comment]
OVH 水冷 R7 5800X 大概 Mgas 在 600 左右 目前售价 $179.99 我有一台闲置的 需要的话可以转租给你 , 直接买的话连接在这 https://www.ovhcloud.com/en/bare-metal/game/game-2/ : (
HZ 价格便宜 但是主板魔改 无法超频

**Comment by lusiwei** [comment]
Mgas这个参数是个什么意思呢？为什么会影响同步速度阿

**Comment by du5** [comment]
这不是参数, 这就是每秒同步的速度指标

**Comment by lusiwei** [comment]
我现在租的AWS每个月都差不多1000美金，这个才$179.99,其他方面的性能能达到同步要求吗

**Comment by du5** [comment]
AWS 有性价比?

**Comment by lusiwei** [comment]
对这硬件方面不是很了解，已经接连换了好几个配置

**Comment by lusiwei** [comment]
一开始用香港阿里云，后来再换AWS,相比之下AWS比阿里云强太多了

**Comment by du5** [comment]
阿里就更没性价比了 : (

**Comment by lusiwei** [comment]
搞这个全节点弄了一个多月，换来换去，现在还没同步下来，网上资料太少了

**Comment by lusiwei** [comment]
我用你这个配置先去同步试试

**Comment by du5** [comment]
该说的都说了 :( 别扯淡了 快开机同步
![image](https://user-images.githubusercontent.com/54979375/181462542-70821648-e0ed-4bb5-be15-214d268dc296.png)

**Comment by du5** [comment]
Execution 是最慢的 其他都是几小时就 ok 我说的 十二天也是指 Execution 的耗时

**Comment by lusiwei** [comment]
好，怎么看网上那些教程一两天甚至10个小时就同步完了，很是不理解，难道我同步的是假的全节点

**Comment by du5** [comment]
以太坊 fast mode

**Comment by lusiwei** [comment]
我看的这个教程 https://learnblockchain.cn/article/3621

**Comment by du5** [comment]
> 我看的这个教程 https://learnblockchain.cn/article/3621

没看人家用快照了 :(

**Comment by du5** [comment]
我闲置那台租的话私聊 https://t.me/mhsoju 150$/mo 季付

**Comment by lusiwei** [comment]
现在怎么不提供完整的全节点快照了

**Comment by du5** [comment]
现在的快照都是全节点快照

**Comment by lusiwei** [comment]
我指的是未修剪过的全节点快照

**Comment by du5** [comment]
存档节点 erigon 7T geth 更大, 你怎么下载, 下好了怎么解压 :(

**Comment by du5** [comment]
> 你这台机器同步到链尖时会有很高延迟吗

?? 不知道你在说什么，机器硬件是完全满足的

**Comment by BNB666666666** [comment]
> > 你这台机器同步到链尖时会有很高延迟吗
> 
> ?? 不知道你在说什么，机器硬件是完全满足的

有没有高网络延迟，好像在国内用自己电脑同步网络延迟有点高啊

**Comment by BNB666666666** [comment]
> 我闲置那台租的话私聊 https://t.me/mhsoju 150$/mo 季付

你这个电报号失效了，还有有联系方式吗？

**Comment by BNB666666666** [comment]
> > OVH 水冷 R7 5800X 大概 Mgas 在 600 左右 目前售价 $179.99 我有一台闲置的 需要的话可以转租给你 , 直接买的话连接在这 https://www.ovhcloud.com/en/bare-metal/game/game-2/ : ( HZ 价格便宜 但是主板魔改 无法超频
> 
> 你这台机器同步到链尖时会有很高延迟吗

有联系方式吗？
