### ISSUE TITLE
How long does it take to catch up?

### ISSUE THREAD

**Issue by ofarukcaki** [BNB48Club/bsc-snapshots#17]
I have downloaded the erigon snapshot and running the erigon for more than **2 days** already, but it still didn't catch up the live blocks and it's coming delayed. eth.syncing calls returns false, but it is syncing, and currently about ~400 blocks behind.

```
> eth.syncing
false
> eth.getBlock('latest').number
20098402.                                  # but the current block is 20098814
```
erigon outputs like this:
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/24359008/182471170-6d4d4471-35ce-4cce-812e-0735d5c484e1.png">

Is this normal that it takes that long while using the snapshot?

**Comment by du5** [comment]
what is the CPU frequency

**Comment by ofarukcaki** [comment]
> what is the CPU frequency

It's c5a.4xlarge ec2 instance from AWS and should be 3.3Ghz or so. After 2-3 days it is synced with the blockchain and now it is running ok

**Comment by ergsm** [comment]
good news!
