### ISSUE TITLE
Node Won't Sync With This Snapshot.

### ISSUE THREAD

**Issue by Zihao-Luo** [BNB48Club/bsc-snapshots#20]
**Start Up Command**
./geth --config ./config.toml --datadir ./mainnet --txlookuplimit 0 --diffsync=true --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000.

**Geth Behaviour/Issue.**
![image](https://user-images.githubusercontent.com/73833947/186782919-ef4f5138-170b-45f9-b841-f9eac248bd1f.png)
Impossible to sync and **currentBlock: 20730694** always stuck at this block number. Bsc.log is spammed with errors related to peer.

**Edit**: CheckSum is correct.

I can run old snapshot that doesn't require flag **pruneancient=true** perfectly fine and only have issues with new snapshots requiring this flag. I also tried **https://github.com/bnb-chain/bsc-snapshots** and it synced perfectly fine.

Any help is appreciated. Thanks in advance.

**Comment by du5** [comment]
pls check the log when geth starts

**Comment by Zihao-Luo** [comment]
> pls check the log when geth starts

![image](https://user-images.githubusercontent.com/73833947/186880319-1362b14f-b031-4b7a-8164-2084dd9545f5.png)

**Comment by PotatoSniper** [comment]
> pls check the log when geth starts


Port **30301, 30303 and 30311** are all enabled.

**Comment by du5** [comment]
try to delete the cache file
```zsh
➜  geth du -h       
16K	./keystore
16K	./geth/keystore
39M	./geth/chaindata/ancient
584G	./geth/chaindata
176K	./geth/lightchaindata
672K	./geth/triecache
211M	./geth/ethash
20M	./geth/nodes
584G	./geth
584G	.
➜  geth rm -rf geth/{nodes,LOCK,triecache,keystore} keystore 
```

**Comment by PotatoSniper** [comment]
> try to delete the cache file
> 
> ```shell
> ➜  du -h       
> 16K	./keystore
> 16K	./geth/keystore
> 39M	./geth/chaindata/ancient
> 584G	./geth/chaindata
> 176K	./geth/lightchaindata
> 672K	./geth/triecache
> 211M	./geth/ethash
> 20M	./geth/nodes
> 584G	./geth
> 584G	.
> ➜  rm -rf geth/{nodes,LOCK,triecache,keystore} keystore 
> ```

Thanks for taking the time to help me. I removed all the files and restarted GETH, but it was still giving me the same errors. I started deleting random files and it works now, but i still don't know what the exact issue was.

**Comment by Zihao-Luo** [comment]
> try to delete the cache file
> 
> ```shell
> ➜  du -h       
> 16K	./keystore
> 16K	./geth/keystore
> 39M	./geth/chaindata/ancient
> 584G	./geth/chaindata
> 176K	./geth/lightchaindata
> 672K	./geth/triecache
> 211M	./geth/ethash
> 20M	./geth/nodes
> 584G	./geth
> 584G	.
> ➜  rm -rf geth/{nodes,LOCK,triecache,keystore} keystore 
> ```

Thanks for taking the time to help me. I removed all the files and restarted GETH, but it was still giving me the same errors. I started deleting random files and it works now, but i still don't know what the exact issue was.

**Comment by KutkovetskyiVolodymyr** [comment]
same issue right now

**Comment by KutkovetskyiVolodymyr** [comment]
![image](https://user-images.githubusercontent.com/25223556/196056499-ab86bf5b-41e3-4ac9-a750-167a97c0d587.png)
