### ISSUE TITLE
no peers ?

### ISSUE THREAD

**Issue by zigzagsui** [BNB48Club/bsc-snapshots#25]
was there a settings modification on last week snapshots ? i am using bnb48 snapshot  + flags (prunenancient) since the beginning of v .12 without issue, but this week i installed 2 nodes and both has peers issue. ( almost no peers, maybe 20 after 2h)   so i reinstalled it with official bsc snapshot , without pruneancient, and no peers issue anymore.(200 peers in 1h)  any idea why ?

**Comment by du5** [comment]
try this https://github.com/BNB48Club/bsc-snapshots/issues/20#issuecomment-1229142471
