### ISSUE TITLE
snapshot download failed

### ISSUE THREAD

**Issue by prathmeshgotoadmins** [BNB48Club/bsc-snapshots#30]
Hi tried to download the snapshot with below command
`wget -O geth.tar.lz4 https://download.bsc-snapshot.workers.dev/geth-20220930.tar.lz4`

but connection is getting closed again and again with below error
`HTTP request sent, awaiting response... 500 Internal Server Error`

**Comment by 48ClubIan** [comment]
This is not a snapshot delivered by BNB48
