### ISSUE TITLE
diff in sync speed from standalone erigon?

### ISSUE THREAD

**Issue by youCantLose** [BNB48Club/bsc-snapshots#32]
since i am in need to sync a bsc client, and since erigon introduced snapshot sync via torrent, i am wondering whether this is still improving sync speed form scratch?

in other words, i know with geth there's a massive improvement, wondering how much if any with erigon, do you have any data on this/anecdotal reports?

thanks!

**Comment by du5** [comment]
time acceleration is at least two weeks

no detailed report on performance
