### ISSUE TITLE
大佬能不能11月7号以后再发行新的erigon快照:(

### ISSUE THREAD

**Issue by BNB666666666** [BNB48Club/bsc-snapshots#34]
我用的小水管宽带下了好几天了，明天就下完了，希望大佬明天（11月6日）不要更新下载地址，不然只能重下了：（（（（（

**Comment by du5** [comment]
恰巧最近维护，已经一周没更新了，不过马上自动化脚本就要开始制作新快照了

**Comment by BNB666666666** [comment]
收到，谢谢  : )

**Comment by temuera** [comment]
@BNB666666666 你下的啥快照，存档的？
