### ISSUE TITLE
[2/16 Headers] No block headers to write in this log period      please HELP!

### ISSUE THREAD

**Issue by BNB666666666** [BNB48Club/bsc-snapshots#35]
![image](https://user-images.githubusercontent.com/117515691/200607645-00fde935-78b2-4af3-b6c8-e4b664c11bef.png)

I uncompressed the 'erigon.22575695.tar.lz4' then run the erigon.           ./erigon --chain=bsc --prune=hrtc --db.pagesize=16k --datadir /run/media/xxx/新加卷/erigondata/erigon --private.api.addr=0.0.0.0:9090 -metrics --metrics.addr=0.0.0.0 --metrics.port=9350 --pprof --pprof.addr=0.0.0.0 --pprof.port=9351 --nat=any --downloader.verify --snap.stop       now it seems stucked : ( . But it can still sync super slowly（ it wrote headers around every2~3h ）. Is it resonable?  What should I do ? thx for response!

解压 'erigon.22575695.tar.lz4' 并运行erigon  （  ./erigon --chain=bsc --prune=hrtc --db.pagesize=16k --datadir /run/media/xxx/新加卷/erigondata/erigon --private.api.addr=0.0.0.0:9090 -metrics --metrics.addr=0.0.0.0 --metrics.port=9350 --pprof --pprof.addr=0.0.0.0 --pprof.port=9351 --nat=any --downloader.verify --snap.stop ）   之后，erigon到第二步时总是提示   [2/16 Headers] No block headers to write in this log period ，但它貌似也不是完全没了进展（大概用了8个小时从22575695区块到了图中的22686288区块），大概过了两三个小时它会显示一次wrote headers，这正常吗？我应该做些什么？求解答！

**Comment by BNB666666666** [comment]
请问怎么换p2p端口到30311

**Comment by BNB666666666** [comment]
这是网络问题吗

**Comment by lusiwei** [comment]
一样的问题，试了所有的方法都没用

**Comment by du5** [comment]
erigon snapshots releases 

 - fix snap error 
 - latest block [22913250](https://bscscan.com/block/22913250)
 - 
https://github.com/BNB48Club/bsc-snapshots#erigon-snapshots

https://snapshots.bnb48.club/erigon.22913250.tar.lz4
