### ISSUE TITLE
怎么会这么这么慢

### ISSUE THREAD

**Issue by BNB666666666** [BNB48Club/bsc-snapshots#36]
![image](https://user-images.githubusercontent.com/117515691/201123652-f53b6a14-193e-409a-82cb-b5dccb4d58ca.png)

之前从0区块同步的时候都有20blocks/s，现在用快照 excution的时候为什么会这么慢？

incredible!!!     X (

**Comment by BNB666666666** [comment]
who can HELP ME :(

**Comment by BNB666666666** [comment]
配置：CPU： 16 cores
           RAM: 64G
           Disk: ssd 2T
           network: 20m/s

**Comment by 48ClubIan** [comment]
mgasps 只有個位數，一秒鐘能追上一個塊簡直燒高香了。snapshot只提供數據，同步慢跟snapshot沒關係。

**Comment by du5** [comment]
Windows 问题转至 erigon issues 讨论

**Comment by BNB666666666** [comment]
我是centos7.9系统，请问有什么解决办法吗

**Comment by BNB666666666** [comment]
> mgasps 只有個位數，一秒鐘能追上一個塊簡直燒高香了。snapshot只提供數據，同步慢跟snapshot沒關係。

同步的时候主要靠的是什么，硬盘吗？还是网络？
