### ISSUE TITLE
Run erigon 2.29.0 error

### ISSUE THREAD

**Issue by BNB666666666** [BNB48Club/bsc-snapshots#37]
![image](https://user-images.githubusercontent.com/117515691/201262586-a291574d-cf14-4de7-9457-49a006cd204e.png)

[xxx@localhost 新加卷]$ ./erigon29
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.

**Comment by du5** [comment]
https://github.com/ledgerwatch/erigon/issues/new/choose

**Comment by du5** [comment]
https://github.com/ledgerwatch/erigon#windows

**Comment by BNB666666666** [comment]
> https://github.com/ledgerwatch/erigon#windows

谢谢，不过我是centos7.9系统，windows教程貌似没有作用

**Comment by du5** [comment]
使用源代码编译试试看，不行建议咨询 erigon 官方社区

**Comment by BNB666666666** [comment]
> 使用源代码编译试试看，不行建议咨询 erigon 官方社区

好的，谢谢。by the way，erigon的版本对excution有影响吗

**Comment by BNB666666666** [comment]
我想用2.29.0，不知道会不会解决excution慢的问题
