### ISSUE TITLE
可以把erigon的快照文件顺便上传一份到阿里云盘吗？

### ISSUE THREAD

**Issue by BNB666666666** [BNB48Club/bsc-snapshots#39]
可以把erigon的快照文件顺便上传一份到阿里云盘吗？

中国的网友三百兆网速用这个链接下载只能跑出5m不到的速度，而且特别不稳定，一下2m/s一下1m/s，下载过程极慢无比。可以的话非常感谢

**Comment by BNB666666666** [comment]
@du5

**Comment by du5** [comment]
No plan
