### ISSUE TITLE
how to run geth by this snapshot?

### ISSUE THREAD

**Issue by hotcoin-walle** [BNB48Club/bsc-snapshots#5]
the [bsc ](https://github.com/bnb-chain/bsc-snapshots)  is 1.6TB

BNB48club's snapshot is 550GB, What are the startup parameters for geth?
I don't know how to config it. 
anyone can help me ?

**Comment by 48ClubIan** [comment]
The snapshot basically means a copy of  `{your node dir}/geth`

So 
1. Stop your running node or follow https://docs.bnbchain.org/docs/validator/fullnode to start a new node without really start `geth`
2. extract the snapshot and replace your original  `{your node dir}/geth` 
3. (Re)start your node. Parameters depends on your own requirements, we can't specify here.

**Comment by hotcoin-walle** [comment]
my startup params.

geth_linux --datadir /bsc/datas --config /bsc/configs/config.toml --http.addr 0.0.0.0 --http.port 8545 --http --http.api eth,net,web3,rpc,txpool,debug --http.corsdomain *  --syncmode snap --cache 8192 --maxpeers 200 --txpool.lifetime 1h30m0s --txlookuplimit=3000000 --diffsync

**Comment by salisbury-espinosa** [comment]
can i get internal transactions from this snapshot? (by debug_traceTransaction)
