### ISSUE TITLE
Can't gracefully shut down with these snapshots

### ISSUE THREAD

**Issue by SomeGuyCalledBru** [BNB48Club/bsc-snapshots#6]
BNBChain's official snapshots work fine, but when attempting to shut down after syncing from this snapshot, I'm getting "Waiting for background transaction indexer to exit", followed by never exiting. My node's been shutting down for 5 hours now.

Ubuntu 20.04, geth 1.1.11. Reproduced on snapshots 18630772, 18615124 and 18583092.

**Comment by SomeGuyCalledBru** [comment]
2. I send `SIGINT` using `kill`. I'm just confused because this doesn't happen when I use official snapshots, doesn't happen when I sync from genesis, BUT happens when I sync from these snapshots.
3. I didn't modify the config.toml, startup command is `nohup ~/nvme1_data/geth_linux --config ~/nvme1_data/config.toml --cache 65536 --maxpeers 1000 --http --http.api web3,eth,net,txpool --http.addr 0.0.0.0 --txpool.pricelimit 5000000000 --txpool.pricebump 5 --txpool.accountslots 15 --txpool.globalslots 2048 --txpool.accountqueue 32 --txpool.globalqueue 768 --txpool.lifetime 48h0m0s`

**Comment by SomeGuyCalledBru** [comment]
> Can you provide some trace before you send SIGINT?

It runs as usual with `Imported new chain segment` and occasional `Snapshot extension registration failed`.

> As you mentioned, I also notice that your node has no peer connected, in another word, your node is not syncing at all. You'd better fix this first, otherwise, there is no point to shut down gracefully or not 'cause it doesn't really matter.

I have 300-400 peers when my node is up. When I send shutdown, I lose all of them as expected. But I still get the `Looking for peers` message during the shutdown, nonstop.

> can you show me the ls result of your ./node and ./node/geth?

I currently erased them because the DB got corrupted after I force killed geth. BUT, I didn't have a node beforehand. I "crafted" the datadir as `{path}/geth/chaindata` and `{path}/geth/triecache` and let geth create everything afterwards. Could this be the culprit(do I need to get a node up beforehand, THEN replace the DB?)

**Comment by 48ClubIan** [comment]
> t



> > Can you provide some trace before you send SIGINT?
> 
> It runs as usual with `Imported new chain segment` and occasional `Snapshot extension registration failed`.
> 
> > As you mentioned, I also notice that your node has no peer connected, in another word, your node is not syncing at all. You'd better fix this first, otherwise, there is no point to shut down gracefully or not 'cause it doesn't really matter.
> 
> I have 300-400 peers when my node is up. When I send shutdown, I lose all of them as expected. But I still get the `Looking for peers` message during the shutdown, nonstop.
> 
> > can you show me the ls result of your ./node and ./node/geth?
> 
> I currently erased them because my DB got corrupted after I force killed geth. BUT, I didn't have a node beforehand. I initially "crafted" and copied the datadir from the snapshot as `{path}/geth` and let geth create everything else afterwards. Basically the node's 1st ever run was from the snapshot and `./{path}` was empty other than `geth` when the node was started. Could this be the culprit(do I need to get a node up beforehand, THEN replace the DB?)

It's fine to have only `geth` dir in your `--datadir` path.

What's your `{path}/geth` looks like? 

It should be like : `chaindata  lightchaindata  LOCK  nodekey  nodes  triecache`

Try to avoid the situation that there is another `geth` containing all the above lies in  `{path}/geth`, the program will consider this as a not correctly initialized node directory.

**Comment by SomeGuyCalledBru** [comment]
`{path}/geth`: `chaindata les.server lightchaindata LOCK nodekey nodes triecache` 
`./{path}`: `lightchaindata  LOCK  nodekey  nodes chaindata triecache geth geth.ipc  keystore`
The `chaindata` that actually has the data is in `{path}/geth`.

Also I just synced from bnb-chain's 20220611 snapshot-I can shut down fine.

**Comment by 48ClubIan** [comment]
> `{path}/geth`: `chaindata les.server lightchaindata LOCK nodekey nodes triecache` `./{path}`: `lightchaindata LOCK nodekey nodes chaindata triecache geth geth.ipc keystore` The `chaindata` that actually has the data is in `{path}/geth`.
> 
> Also I just synced from bnb-chain's 20220611 snapshot-I can shut down fine.

This looks strange to me, your `{path}` contains something don't belong here.
I think somehow you messed up your node directory.

**Comment by 48ClubIan** [comment]
> `{path}/geth`: `chaindata les.server lightchaindata LOCK nodekey nodes triecache` `./{path}`: `lightchaindata LOCK nodekey nodes chaindata triecache geth geth.ipc keystore` The `chaindata` that actually has the data is in `{path}/geth`.
> 
> Also I just synced from bnb-chain's 20220611 snapshot-I can shut down fine.
I suggest you use a brand new directory to run a node next time.
Can't say more based on what I've seen now.

**Comment by SomeGuyCalledBru** [comment]
I'm guessing something was my mistake every time I synced from this snapshot(I don't know what exactly really), applied all the suggestions, fixed my datadir and now I can properly shut down. Thanks for the help.
